# Generated by Django 4.2.7 on 2023-12-11 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destination',
            field=models.CharField(blank=True, default=None, max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.ForeignKey(blank=True, db_column='person', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
